# Image de base
FROM mysql:8.4.6

# Mot de passe ROOT du serveur de base de données
ENV MYSQL_ROOT_PASSWORD=azer
# Nom de la base de données qui sera créée au 1er démarrage du conteneur
ENV MYSQL_DATABASE=mydatabase
# Nom d'utilisateur pour se connecter à la base de données
ENV MYSQL_USER=mike
# Mot de passe pour se connecter à la base de données
ENV MYSQL_PASSWORD=1234

