# Image de base
FROM mongo:8.0.14-noble

# Nom de la base de données qui sera créée au 1er démarrage du conteneur (pouet pouet à vérifier)
ENV MONGO_INITDB_DATABASE=mydatabase
# Nom d'utilisateur pour se connecter au serveur
ENV MONGO_INITDB_ROOT_USERNAME=mike
# Mot de passe pour se connecter à la base de données
ENV MONGO_INITDB_ROOT_PASSWORD=1234

