name: olivier-nodejs
services:
  web:
    image: node:24.14.0-alpine
    container_name: olivier-nodejs-app
    ports:
      - "3333:80"
    volumes:
      - ./src/:/app/
    working_dir: /app
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: sh
  